spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./demodb
    #url: jdbc:h2:mem:demodb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false # N+1
  h2:
    console:
      enabled: true
  profiles:
    default: dev
#  security:
#    user:
#      password: s3cr3t


#server:
#  servlet:
#    session:
#      timeout: 60s

logging:
  level:
    com.example: trace
    org.springframework.security: trace

sample-app:
  jwt:
    secret: c56222fa88ed489daae109e38d65afd0
  app-name: Sample app
  request-timeout: 30000
