spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:./proddb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: false

sample-app:
  request-timeout: 10000